include: package:flutter_lints/flutter.yaml
linter:
  rules:
    non_constant_identifier_names: false
    file_names: false
    constant_identifier_names: false
    use_key_in_widget_constructors: false