name: textpop
description: A new Flutter project.
publish_to: 'none'
version: 1.0.5+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  dio: ^5.6.0
  eraser: ^3.0.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  flutter_launcher_icons: ^0.13.1
  flutter_link_previewer: ^3.2.2
  flutter_local_notifications: ^17.2.2
  flutter_native_splash: ^2.3.2
  flutter_webrtc: ^0.11.6+hotfix.1
  fluttertoast: ^8.2.2
  google_sign_in: ^6.1.4
  image_cropper: ^8.0.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.1
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.3.0
  photo_view: ^0.15.0
  provider: ^6.0.5
  share_plus: ^10.0.0
  sign_in_with_apple: ^6.1.2
  signalr_core: ^1.1.2
  sqflite: ^2.2.8+4
  url_launcher: ^6.1.14
  wakelock_plus: ^1.1.4

dependency_overrides:
  image_gallery_saver: # support for android gradle 8.0 https://github.com/hui-z/image_gallery_saver/pull/295
    git:
      url: https://github.com/knottx/image_gallery_saver.git
      ref: knottx-latest

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/Light/ArrowBack.png
    - assets/Images/Light/Account/LoginCube.png
    - assets/Images/Light/Account/FacebookLogo.png
    - assets/Images/Light/Account/GoogleLogo.png
    - assets/Images/Light/Account/AppleLogo.png
    - assets/Images/Light/Account/Avatar.png
    - assets/Images/Light/Account/ImageIcon.png
    - assets/Images/Light/Account/RightArrow.png
    - assets/Images/Light/Chat/Setting.png
    - assets/Images/Light/Chat/Pencil.png
    - assets/Images/Light/Chat/Ban.png
    - assets/Images/Light/Chat/LeaveVideoChat.png
    - assets/Images/Light/Chat/EnterVideoChat.png
    - assets/Images/Light/Chat/SwitchCamera.png
    - assets/Images/Light/Chat/AudioTrackOff.png
    - assets/Images/Light/Chat/VideoTrackOff.png
    - assets/Images/Light/Chat/AudioTrackOn.png
    - assets/Images/Light/Chat/VideoTrackOn.png
    - assets/Images/Light/Setting/Mode.png
    - assets/Images/Light/Setting/Language.png
    - assets/Images/Light/Setting/About.png
    - assets/Images/Light/Setting/Delete.png
    - assets/Images/Light/Setting/Logout.png
    - assets/Images/Light/Setting/PrivacyPolicy.png
    - assets/Images/Light/Setting/TermsAndConditions.png
    - assets/Images/Dark/ArrowBack.png
    - assets/Images/Dark/Account/LoginCube.png
    - assets/Images/Dark/Account/FacebookLogo.png
    - assets/Images/Dark/Account/GoogleLogo.png
    - assets/Images/Dark/Account/AppleLogo.png
    - assets/Images/Dark/Account/Avatar.png
    - assets/Images/Dark/Account/ImageIcon.png
    - assets/Images/Dark/Account/RightArrow.png
    - assets/Images/Dark/Chat/Setting.png
    - assets/Images/Dark/Chat/Pencil.png
    - assets/Images/Dark/Chat/Ban.png
    - assets/Images/Dark/Chat/LeaveVideoChat.png
    - assets/Images/Dark/Chat/EnterVideoChat.png
    - assets/Images/Dark/Chat/SwitchCamera.png
    - assets/Images/Dark/Chat/AudioTrackOff.png
    - assets/Images/Dark/Chat/VideoTrackOff.png
    - assets/Images/Dark/Chat/AudioTrackOn.png
    - assets/Images/Dark/Chat/VideoTrackOn.png
    - assets/Images/Dark/Setting/Mode.png
    - assets/Images/Dark/Setting/Language.png
    - assets/Images/Dark/Setting/About.png
    - assets/Images/Dark/Setting/Delete.png
    - assets/Images/Dark/Setting/Logout.png
    - assets/Images/Dark/Setting/PrivacyPolicy.png
    - assets/Images/Dark/Setting/TermsAndConditions.png


flutter_launcher_icons:  
  # flutter pub run flutter_launcher_icons 
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
  remove_alpha_ios: true


flutter_native_splash:
  # dart run flutter_native_splash:create / dart run flutter_native_splash:remove
  color: "#f6bd60"
  image: assets/SplashIcon.png
  color_dark: "#2d2727"
  image_dark: assets/SplashIcon.png

  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.  
    color: "#f6bd60"
    image: assets/SplashIconAndroid12.png
    color_dark: "#2d2727"
    image_dark: assets/SplashIconAndroid12.png